export const originArr = [
  "African-American",
  "Anglo-American",
  "Cajun/Creole",
  "Chinese-American",
  "English",
  "Finnish",
  "French-Canadian",
  "German-American",
  "Irish",
  "Irish-American",
  "Jewish-American",
  "Latino/Spanish",
  "Native American",
  "Pennsylvania Dutch",
  "Polynesian",
  "Portuguese",
  "Russian-American",
  "Scottish",
  "Scottish-American",
];
