export const regionArr = [
  "Appalachia",
  "British Isles",
  "Canada",
  "Caribbean",
  "Central America",
  "Europe",
  "Great Lakes",
  "Mexico",
  "Mid-Atlantic",
  "Midwest",
  "New England",
  "Northwest",
  "Ozarks",
  "Pacific Islands",
  "Plains",
  "Sea Islands",
  "South",
  "South American",
  "Southwest",
  "West",
  "Widespread",
];
