export const rhythmicElementArr = [
  "anacrusis",
  "dotted half note",
  "eighth rest",
  "half note",
  "half rest",
  "quarter rest",
  "quarter rest/ti",
  "ri-tim",
  "ri-ti-ti",
  "syn-co-pa",
  "ta ti-ti",
  "tam",
  "tam-ti",
  "ta-ti",
  "ti rest/ rest ti",
  "tim-ri",
  "tim-ri-ti",
  "tiri-ti",
  "tiri-tiri",
  "ti-ta",
  "ti-tam",
  "ti-tiri",
  "ti-ti-ti",
  "triplet",
  "whole note/whole rest",
];
