export const scaleArr = [
  "Bimodal",
  "Bitonic",
  "Blues",
  "Dorian",
  "Hexachord",
  "Hexatonic",
  "Lydian",
  "Major",
  "Major (inc)",
  "Minor/Harmonic",
  "Minor/Melodic",
  "Minor/Natural",
  "Mixolydian",
  "Other",
  "Pentachord",
  "Pentatonic",
  "Phrygian",
  "Tetrachord",
  "Tetratonic",
  "Trichord",
  "Tritonic",
];
