export const subjectArr = [
  "Animals",
  "Birds",
  "Colors",
  "Counting",
  "Crime and Punishment",
  "Death and Afterlife",
  "Fishes",
  "Food and Drink",
  "Freedom",
  "Greeting and Farewell",
  "Heroism and Villany",
  "Historical",
  "Holiday",
  "Home and Family",
  "Insects",
  "Love and Courtship",
  "Movement",
  "Music",
];
