export const songs = [
  {
    id: "00001",
    title: "Clair de lune",
    author: "Claude Debussy",
    music_mp3: null,
    sheet_music_pdf: null,
    length: 5 * 60 + 22,
    tags: {
      origin: [],
      region: ["Europe"],
      state: [],
      subject: [],
      songType: [],
      schoolGradeLevel: ["High School"],
      tonalCenter: [],
      scale: [],
      toneSet: [],
      melodicRange: [],
      melodicElement: [],
      melodicMotive: [],
      rhythmicElement: [],
      meter: [],
      formType: [],
      formalAnalysis: [],
      gameType: [],
    },
  },
  {
    id: "00001",
    title: "Clair de lune",
    author: "Claude Debussy",
    music_mp3: null,
    sheet_music_pdf: null,
    length: 5 * 60 + 22,
    tags: {
      origin: [],
      region: ["Europe"],
      state: [],
      subject: [],
      songType: [],
      schoolGradeLevel: ["High School"],
      tonalCenter: [],
      scale: [],
      toneSet: [],
      melodicRange: [],
      melodicElement: [],
      melodicMotive: [],
      rhythmicElement: [],
      meter: [],
      formType: [],
      formalAnalysis: [],
      gameType: [],
    },
  },
  {
    id: "00001",
    title: "Clair de lune",
    author: "Claude Debussy",
    music_mp3: null,
    sheet_music_pdf: null,
    length: 5 * 60 + 22,
    tags: {
      origin: [],
      region: ["Europe"],
      state: [],
      subject: [],
      songType: [],
      schoolGradeLevel: ["High School"],
      tonalCenter: [],
      scale: [],
      toneSet: [],
      melodicRange: [],
      melodicElement: [],
      melodicMotive: [],
      rhythmicElement: [],
      meter: [],
      formType: [],
      formalAnalysis: [],
      gameType: [],
    },
  },
];
